name: fitness_coach_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
